server:
  port: 8903
logging:
  level:
    root: WARN
    org.springframework: INFO
    com.chinadaas: INFO
spring:
  application:
    name: cloud-stream-kafka-consumer8903
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.137.201:9092,192.168.137.202:9092,192.168.137.203:9092
          configuration:
            max.poll.records: 10
            max.poll.interval.ms: 50000
            session.timeout.ms: 50000
            auto-add-partitions: true  #新增
        bindings:
          input:
            consumer:
              autoCommitOffset: false
      bindings:
        input:
          destination: test_topic_2020
          group: xgx
          consumer:
            concurrency: 1
            partitioned: true
            auto-bind-dlq: true
            republish-to-dlq: true
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
