server:
  port: 8901
logging:
  level:
    root: WARN
    org.springframework: INFO
    com.chinadaas: INFO
spring:
  application:
    name: cloud-stream-kafka-provider
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.137.201:9092,192.168.137.202:9092,192.168.137.203:9092
          configuration:
            max.poll.records: 10
            max.poll.interval.ms: 50000
            session.timeout.ms: 50000
        bindings:
          input:
            consumer:
              autoCommitOffset: true
      bindings:
        output:
          destination: test_topic
          content-type: text/plain
          producer:
            partitionCount: 3
            #headerMode: raw

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
